language: python
python:
  - "3.8"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest